exporters:
  otlp/dash0:
    endpoint: ingress.us-west-2.aws.dash0.com:4317
    headers:
      Authorization: "your key"
      Dash0-Dataset: "vitors-dataset"

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

processors:
  batch: {}
  
  resourcedetection:
    detectors: [env, system]
    system:
      hostname_sources: ["os"]

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"


  hostmetrics:
    root_path: /hostfs
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      load: {}
      disk: {}
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      network: {}
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      processes: {}


service:
  extensions:

  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/dash0]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [otlp/dash0]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/dash0]
